### ISSUE TITLE
Unwated tag injection when mouse sits over suggest box

### ISSUE THREAD

**Issue by bxlbjorn** [amsify42/jquery.amsify.suggestags#26] opened 2019-10-10 14:53 UTC
When the mouse pointer sits somewhere below the input field and you start typing, the suggested tag under the pointer gets injected immediately. This behaviour should only happen when the mouse is moving.

**Comment by amsify42** [comment] 2019-10-31 18:44
I tried to avoid hover on suggested items when we start typing and mouse pointer is just below the input, but this seems to be expected behavior of *hover* event.
The moment suggested items are appearing, hover event is getting triggered as mouse is just over those items.

If you have any solution for it, please let me know else I will close the issue.

**Closed** 2019-11-20 16:57 UTC
