### ISSUE TITLE
How to use with Vietnamese?

### ISSUE THREAD

**Issue by canomi** [amsify42/jquery.amsify.suggestags#72] opened 2021-04-23 02:54 UTC
My suggestions array is:
```
 {
  "suggestions": [
    "du lịch Việt Nam",
    "lịch trình du lịch Việt Nam",
    "phượt Việt Nam",
    "Việt Nam",
    "check-in Việt Nam",
    "hạ long việt nam",
    "hoa đào ở việt nam",
    "mùa hoa gạo việt nam"
  ]
}
```
When I typed: "Việt Nam" or "việt nam", it worked, it showed a list of tags
However when I typed "Viet Nam" or "viet nam", it didn't work, not show a list of tags.
How can i fix it for Vietnamese.
Thank you so much

**Comment by amsify42** [comment] 2021-05-09 17:13
Sorry for the very late reply. Currently the suggestions filtering does not do such thing. If you want to do custom check while filtering the suggestions, you can check this option and try writing some custom condition in that callback function.
https://github.com/amsify42/jquery.amsify.suggestags#suggestmatch

**Comment by amsify42** [comment] 2021-08-31 06:45
I hope the last message helped you find the solution for your problem. I am closing the issue, if you think the problem is not solved you can reopen it.

**Closed by amsify42** 2021-08-31 06:45 UTC
